language: cpp
sudo: required

matrix:
  include:
    - env: ARCH=x86_64
      addons:
        apt:
          update: true
          packages:
            - libmagic-dev
            - libjpeg-dev
            - libpng-dev
            - cimg-dev
            - automake  # required for patchelf
    - env: ARCH=i386
      addons:
        apt:
          packages:
            - gcc-multilib
            - g++-multilib
            - cimg-dev
            - automake  # required for patchelf
      before_script:
        - sudo -E apt-get install -y libmagic-dev:i386 libjpeg-dev:i386 libpng-dev:i386

install:
  - git clone https://github.com/NixOS/patchelf.git
  - cd patchelf
  - ./bootstrap.sh
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - sudo make install
  - cd ..
  - rm -rf patchelf

script:
  - travis/build.sh

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh linuxdeploy*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
