language: cpp
sudo: required

addons:
  apt:
    update: true
    packages:
      - libboost-regex1.55-dev
      - libboost-filesystem1.55-dev
      - libmagick++-dev
      - libmagic-dev
      - automake  # required for patchelf

install:
  - git clone https://github.com/NixOS/patchelf.git
  - cd patchelf
  - ./bootstrap.sh
  - ./configure --prefix=/usr
  - make -j$(nproc)
  - sudo make install
  - cd ..
  - rm -rf patchelf

script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  # deploy patchelf which is a dependency of linuxdeploy
  - LINUXDEPLOY_ARGS=("--init-appdir" "--appdir" "AppDir" "-e" "bin/linuxdeploy" "-i" "../resources/linuxdeploy.png" "--create-desktop-file" "-e" "/usr/bin/patchelf" "-e" "/usr/bin/convert)
  - bin/linuxdeploy "${LINUXDEPLOY_ARGS[@]}"
  # verify that an AppImage can be built
  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
  - chmod +x appimagetool-x86_64.AppImage
  - ./appimagetool-x86_64.AppImage AppDir
  # verify that the resulting AppImage works
  - ./linuxdeploy*.AppImage "${LINUXDEPLOY_ARGS[@]}"

after_success:
  - ls -lh
  # make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh linuxdeploy*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
